# Prefix : Project Name
name: Deploy-Changes

on: 
  workflow_dispatch:
    inputs:
      ManualApprove:
        description: "Deploy Changes"
        required: true
        default: "main"
      # ReleaseVersion:
      #   description: "Release Version"
      #   required: true
      #   type: string
        


jobs:
  deploy-changes:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye-slim
    steps:
      ## Get the source code to the machine in the current directory
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Print Output
        run: |
          echo "This is to deploy changes"

  release-project:
    runs-on: ubuntu-latest
    needs: deploy-changes
    container:
      image: debian:bullseye-slim
    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ githuyb.run_number }}
          release_name: Release ${{ githuyb.run_number }}