# Prefix : Project Name
name: Deploy-Changes

on: 
  workflow_dispatch:
    inputs:
      ManualApprove:
        description: "Deploy Changes"
        required: true
        default: "main"
      ReleaseVersion:
        description: "Release Version"
        required: true
        type: string
        


jobs:
  deploy-changes:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye-slim
    steps:
      ## Get the source code to the machine in the current directory
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Print Output
        run: |
          echo "This is to deploy changes"