# Prefix : Project Name
name: Create-Release

on: 
  workflow_dispatch:
    inputs:
      ManualApprove:
        description: "Deploy Changes"
        required: true
        default: "main"
      ReleaseVersion:
        description: "Release Version"
        required: true
        type: string
      TagVersion:
        description: "Tag Version"
        required: true
        type: string
        

  release-project:
    runs-on: ubuntu-latest
    needs: deploy-changes
    container:
      image: debian:bullseye-slim
    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:  ${{ github.event.inputs.TagVersion }}
          release_name: Release  ${{ github.event.inputs.ReleaseVersion }}
          body: |
            Deploy : ${{ github.run_number }}