# Prefix : Project Name
name: Create-Release

on: 
  push:
    tags:
    - '*'
  # workflow_dispatch:
  #   inputs:
  #     ManualApprove:
  #       description: "Deploy Changes"
  #       required: true
  #       default: "main"
  #     ReleaseVersion:
  #       description: "Release Version"
  #       required: true
  #       type: string
  #     TagVersion:
  #       description: "Tag Version"
  #       required: true
  #       type: string
        
jobs:
  release-project:
    # runs-on: ubuntu-latest
    # # needs: deploy-changes
    # container:
    #   image: debian:bullseye-slim
    # steps:
    #   - name: Create GitHub Release
    #     uses: actions/create-release@v1
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     with:
    #       tag_name:  ${{ github.event.inputs.TagVersion }}
    #       release_name: Release  ${{ github.event.inputs.ReleaseVersion }}
    #       body: |
    #         Deploy : ${{ github.run_number }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,foo/*.txt"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}